### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by FlatronSamatron** [FlatronSamatron/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by necket** [comment]
https://www.instagram.com/realdonaldtrump
https://www.facebook.com/POTUS
https://twitter.com/potus
