### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by FlatronSamatron** [FlatronSamatron/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by necket** [comment]
June 14, 1946
Donald Trump is Born
in Queens, New York.

June 14, 1946 Donald Trump is Born in Queens, New York.

1959 Leaves for the New York Military Academy

October 6, 1973 The US. Justice Department sues the Trump Organization, charging that it frequently violated the Fair Housing Act by discriminating against black potential buyers.

July 1982 With Mayor Ed Koch, celebrates the completion of Trump Tower in Manhattan.

1987 Publishes The Art of the Deal. which spends 51 weeks on the New York Times list.

January 1989 First appears on the cover of rime.

1990 Is removed from the Forbes 400 list, not to be reinstated until 1996.

1996 Buys the Miss Universe Organization.

January 8, 2004 The Apprentice premieres.

January 6, 2007 Receives star on the Hollywood Walk of Fame.

January 8, 2004 The Apprentice premieres.

June 16, 201S Announces his bid for the U.S. presidency in a speech that included remarks about Mexican immigrants being "rapists" and drug dealers.
